# Generated by Django 4.1.12 on 2024-03-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="object_collector",
            field=models.ForeignKey(
                db_column="ObjectCollector",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.person",
                verbose_name="initials of the person who collected the sample",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="p_id",
            field=models.AutoField(
                db_column="PID",
                primary_key=True,
                serialize=False,
                verbose_name="unique db id of the person",
            ),
        ),
    ]
