# Generated by Django 4.1.12 on 2024-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_object_object_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sampletype",
            name="sample_type_units",
        ),
    ]
