# Generated by Django 4.1.12 on 2024-03-29 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_sampletype_sample_type_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.ForeignKey(
                db_column="SampleType",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.sampletype",
                to_field="sample_type_code",
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="sample_type_code",
            field=models.CharField(
                db_column="sample_type_code",
                max_length=7,
                unique=True,
                verbose_name="7 digit code of measurment types",
            ),
        ),
    ]
