# Generated by Django 4.1.12 on 2024-04-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_sample_sample_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "activitytype_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "activity_name",
                    models.CharField(
                        db_column="activity_name",
                        max_length=20,
                        unique=True,
                        verbose_name="name i.e Watering, Crop",
                    ),
                ),
                (
                    "activity_unit",
                    models.CharField(
                        db_column="activity_unit",
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="name i.e Watering, Crop",
                    ),
                ),
                ("created_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "verbose_name_plural": "ActivityTypes",
                "db_table": "tbl_activity_types",
            },
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="activity_db_timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="sample_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="weather",
            old_name="objectweight_db_timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="objectweight",
            name="objectweight_db_timestamp",
        ),
        migrations.AddField(
            model_name="instrument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="objectweight",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="sampletype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.ForeignKey(
                db_column="activity_type",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.activitytype",
            ),
            preserve_default=False,
        ),
    ]
